<?php

declare(strict_types=1);

namespace Knossos\Query;

use Closure;
use PDO;

/**
 * Renders a compact, deterministic markdown orientation brief from the graph,
 * sized for a CLAUDE.md/AGENTS.md section. Sections are appended in priority
 * order until the character budget is spent; whole sections are omitted (and
 * reported) rather than truncated mid-list.
 */
final readonly class AgentBriefService extends AbstractArchitectureQueryService
{
    private const FRAMEWORK_PREFIXES = ['laravel', 'symfony', 'django', 'fastapi', 'nextjs', 'nestjs', 'react', 'vue'];

    public function __construct(PDO $pdo, ?Closure $clock, private GraphTopologyQueryService $topology)
    {
        parent::__construct($pdo, $clock);
    }

    public function exportAgentBrief(string $projectId, int $maxChars = 4000): ResultEnvelope
    {
        if ($maxChars < 1000 || $maxChars > 20_000) {
            throw new \InvalidArgumentException('max_chars must be between 1000 and 20000.');
        }
        $project = $this->project($projectId);
        $counts = $this->counts($projectId);
        $scannedAt = $this->scannedAt((string) $project['active_scan_id']);

        $head = sprintf(
            "# %s — architecture brief\n\nGenerated by Knossos from the scan of %s: %d files, %d components, %d relationships (%s).\n",
            $project['name'],
            $scannedAt ?? 'the active snapshot',
            $counts['files'],
            $counts['nodes'],
            $counts['edges'],
            $counts['languages'] === '' ? 'language mix unknown' : $counts['languages'],
        );
        $closing = "\n_Generated by the Knossos MCP server. For live answers, call `scan_project` on this repository, then query the returned project_id with `architecture_summary`, `impact_analysis`, or `explain_flow`._\n";

        $sections = [
            'boundaries' => $this->boundariesSection($projectId),
            'entry_points' => $this->entryPointsSection($projectId),
            'key_hubs' => $this->hubsSection($projectId),
            'framework_signals' => $this->frameworksSection($projectId),
        ];
        $markdown = $head;
        $omitted = [];
        foreach ($sections as $name => $section) {
            if ($section === null) {
                continue;
            }
            if (strlen($markdown) + strlen($section) + strlen($closing) <= $maxChars) {
                $markdown .= $section;
            } else {
                $omitted[] = $name;
            }
        }
        $markdown .= $closing;

        if (strlen($markdown) > $maxChars) {
            // Even the always-kept head + closing overran the budget (e.g. a very
            // long project name). Drop every section — none of them could have
            // fit anyway — and, as a last resort, truncate the head itself so the
            // closing pointer is never lost.
            $omitted = array_values(array_unique(array_merge($omitted, array_keys($sections))));
            $markdown = $head . $closing;
            if (strlen($markdown) > $maxChars) {
                $head = substr($head, 0, max(0, $maxChars - strlen($closing)));
                $markdown = $head . $closing;
            }
        }

        return new ResultEnvelope(
            $projectId,
            (string) $project['active_scan_id'],
            sprintf('Generated a %d-character agent brief.', strlen($markdown)),
            ['markdown' => $markdown, 'omitted_sections' => $omitted, 'max_chars' => $maxChars],
            [],
            ['The brief reflects the last scan, not the working tree; regenerate after significant changes.'],
        );
    }

    /** @return array{files: int, nodes: int, edges: int, languages: string} */
    private function counts(string $projectId): array
    {
        $count = function (string $sql) use ($projectId): int {
            $statement = $this->pdo->prepare($sql);
            $statement->execute(['project' => $projectId]);
            return (int) $statement->fetchColumn();
        };
        $languages = $this->pdo->prepare(
            'SELECT language, COUNT(*) AS files FROM files WHERE project_id = :project GROUP BY language ORDER BY files DESC, language',
        );
        $languages->execute(['project' => $projectId]);
        $parts = array_map(
            static fn(array $row): string => sprintf('%s: %d', $row['language'], $row['files']),
            $languages->fetchAll(),
        );
        if (count($parts) > 5) {
            $remaining = count($parts) - 5;
            $parts = array_slice($parts, 0, 5);
            $parts[] = sprintf('+%d more', $remaining);
        }
        return [
            'files' => $count('SELECT COUNT(*) FROM files WHERE project_id = :project'),
            'nodes' => $count('SELECT COUNT(*) FROM nodes WHERE project_id = :project'),
            'edges' => $count('SELECT COUNT(*) FROM edges WHERE project_id = :project'),
            'languages' => implode(', ', $parts),
        ];
    }

    private function scannedAt(string $scanId): ?string
    {
        $statement = $this->pdo->prepare('SELECT finished_at FROM scans WHERE id = :id');
        $statement->execute(['id' => $scanId]);
        $finished = $statement->fetchColumn();
        return is_string($finished) ? $finished : null;
    }

    private function boundariesSection(string $projectId): ?string
    {
        $statement = $this->pdo->prepare(
            'SELECT b.name, b.source, COUNT(bm.node_id) AS members FROM boundaries b ' .
            'LEFT JOIN boundary_memberships bm ON bm.boundary_id = b.id ' .
            'WHERE b.project_id = :project GROUP BY b.id ORDER BY members DESC, b.name LIMIT 10',
        );
        $statement->execute(['project' => $projectId]);
        $rows = $statement->fetchAll();
        if ($rows === []) {
            return null;
        }
        $lines = array_map(
            static fn(array $row): string => sprintf('- %s (%s, %d members)', $row['name'], $row['source'], $row['members']),
            $rows,
        );
        return "\n## Boundaries\n\n" . implode("\n", $lines) . "\n";
    }

    private function entryPointsSection(string $projectId): ?string
    {
        $statement = $this->pdo->prepare(
            'SELECT n.display_name, n.kind, f.relative_path FROM nodes n LEFT JOIN files f ON f.id = n.file_id ' .
            "WHERE n.project_id = :project AND (n.kind IN ('route', 'command', 'endpoint') OR n.id IN (" .
            'SELECT node_id FROM classifications WHERE project_id = :project AND role IN (' .
            "'application.controller', 'application.command', 'application.entry_point', 'laravel.controller', 'laravel.command')" .
            ')) ORDER BY n.kind, n.canonical_name LIMIT 12',
        );
        $statement->execute(['project' => $projectId]);
        $rows = $statement->fetchAll();
        if ($rows === []) {
            return null;
        }
        $lines = array_map(
            static fn(array $row): string => sprintf(
                '- %s (%s)%s',
                $row['display_name'],
                $row['kind'],
                $row['relative_path'] === null ? '' : ' — ' . $row['relative_path'],
            ),
            $rows,
        );
        return "\n## Entry points\n\n" . implode("\n", $lines) . "\n";
    }

    private function hubsSection(string $projectId): ?string
    {
        $hubs = $this->topology->architectureHealth($projectId, limit: 5)->data['hubs'];
        if ($hubs === []) {
            return null;
        }
        $lines = array_map(
            static fn(array $hub): string => sprintf(
                '- %s (%s, degree %d)',
                $hub['component']['display_name'],
                $hub['component']['kind'],
                $hub['metrics']['in_degree'] + $hub['metrics']['out_degree'],
            ),
            $hubs,
        );
        return "\n## Key hubs (most depended-on)\n\n" . implode("\n", $lines) . "\n";
    }

    private function frameworksSection(string $projectId): ?string
    {
        $statement = $this->pdo->prepare('SELECT DISTINCT role FROM classifications WHERE project_id = :project ORDER BY role');
        $statement->execute(['project' => $projectId]);
        $signals = [];
        foreach ($statement->fetchAll(PDO::FETCH_COLUMN) as $role) {
            $prefix = explode('.', (string) $role, 2)[0];
            if (in_array($prefix, self::FRAMEWORK_PREFIXES, true)) {
                $signals[$prefix] = true;
            }
        }
        if ($signals === []) {
            return null;
        }
        return "\n## Framework signals\n\n" . implode(', ', array_keys($signals)) . "\n";
    }
}
